### ISSUE TITLE
Inclusion on F-droid

### ISSUE THREAD

**Issue by proletarius101** [RikkaApps/SaveCopy#2]
Hi, I'm trying to make this app list on F-droid. There are some questions I need to confirm with you:
- Do you agree that we list this app on F-droid?
- What license do you grant under (if any)?
- Do you have any donation links? (optional)

Thank you for making this useful tool :smiley:

**Comment by RikkaW** [comment]
Sorry, but this application is not intended to release on the F-Droid (at least for now).

**Comment by IzzySoft** [comment]
@RikkaW would you be OK if I'd take it into [my repo](https://apt.izzysoft.de/fdroid) (I've been asked to)? Knowing the license you chose would be appreciated anyway :wink:

**Comment by IzzySoft** [comment]
@RikkaW any chance for the license being mentioned?

**Comment by IzzySoft** [comment]
@RikkaW Any idea about the license yet?

**Comment by RikkaW** [comment]
@IzzySoft Sorry for the delay in responding.

It is always welcome to pull apks in GitHub release here and publish them on your own F-Droid repo.

We just don't want others to distribute the apk compiled on their own (that's why we don't want to release RikkaApps on the F-Droid official repo), distribute the apk compiled by us is always OK.

**Comment by IzzySoft** [comment]
Thanks @RikkaW – for the explicit permission and the license! I do understand the problem (one of my products was affected by such a case several years ago: someone else got paid for my work, and users turned to me for support – so I know what you're talking about).

As for F-Droid: there're always "reproducible builds" where, when comparison succeeds, F-Droid takes the APK signed by the dev, adds its own on top, and uses that dual-signed APK in their repo (and if comparison fails, no APK is published). Should you be interested in that, just let me know and I can point you to the proper resources. I'm not an Android dev myself, so pointing often is the only thing I can do :laughing:
